---
- name: install base packages (Debian)
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
  sudo: true
  when: ansible_pkg_mgr == 'apt'

- name: Listen on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp='^bind-address' line='bind-address            = 0.0.0.0'
  sudo: yes
