---
- name: Create new EC2 instances
  connection: local
  ec2:
    region: "{{ item.aws_region }}"
    key_name: "{{ item.key_name }}"
    instance_type: "{{ item.ec2_instance_type }}"
    image: "{{ item.ami_image }}"
    wait: "{{ item.wait }}"
    user_data: "{{ lookup('file', item.user_data_file) }}"
    group: "{{ item.group }}"
    instance_tags: "{{ item.instance_tags }}"
    zone: "{{ item.zone }}"
    vpc_subnet_id: "{{ item.vpc_subnet_id }}"
    exact_count: "{{ item.exact_count }}"
    count_tag: "{{ item.count_tag }}"
  with_items: aws_ec2
  register: ec2

- name: Associate new EIP to the instance
  connection: local
  ec2_eip:
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: ec2.results[0].instances
